### ISSUE TITLE
Stations and seismic phases used for location

### ISSUE THREAD

**Issue by Cthuulhaa** [alomax/NonLinLoc#10]
Hello Anthony,

regarding the seismic location, in particular of local events, do you have any idea how it can affect the location with NonLinLoc only to use the first P- and S-arrival times, without making any distinction between, for example, Pg and  Pn. My detected arrival times are automatically produced and they are simply P- and/or S-arrival times.

Is there any limitation in the epicentral distance for the seismic stations used for the seismic location to obtain an accurate depth/hypocenter?

Thank you!
Catalina

**Comment by alomax** [comment]
Hello Catalina

> only to use the first P- and S-arrival times

With NonLinLoc or any similar location code, the pick phase types should ideally match the phase type of the used travel times. So picks might be labelled Pg, Pn, Sg, Sn, etc and the corresponding travel-time tables would be available for each phase type. This is done in practice for teleseismic location (e.g. with Pg, P, PKP etc), but rarely for routine regional, local or microseismic location. 
For the latter, typical practice with NLL and other systems is to calculate and tabulate *first arrival times*, which will typically be Pg/Sg at close distances (e.g. < 80-120km Pg/Pn cross-over distance) and Pn/Sn at greater distances. In this case, all picks and all travel time tables are labelled simply P or S. If the picks are correctly labelled and the velocity model is fairly good for the area (e.g. good 3D, or good 1D layered and the true earth is ~flat layered), this procedure works adequately for most purposes.
In NLL, Grid2Time uses a first-arrival, finite-differences travel-time calculation (Podvin-Lecomte), so the travel-time tables are first arrivals, usually labelled P and S. The picks should then be labelled simply P and S. If the observed picks have other labels, they can be mapped to P and S with LOCPHASEID.

> Is there any limitation in the epicentral distance for the seismic stations used for the seismic location to obtain an accurate depth/hypocenter?

A general rule for local/regional/microseismic location is that there must be a station or stations with P and S readings within a distance of approximately the true source depth in order to get an accurate depth. This rule can give a depth with small, formal depth uncertainty, but the true absolute depth error will still depend on the accuracy of the velocity model. Usually velocity models are greatly over-simplified and likely have low accuracy, this error is mostly not accounted for in the formal location errors.

A more general rule might be that an accurate depth can only be obtained with either:

1. Observations nearby and all around the hypocenter, so both epicenter and depth are constrained mainly by the *geometry* of the rays leaving the source, and less by travel-times in a likely inaccurate and over-simplified velocity model. This geometry is almost never available, as stations are usually at the surface and "see" the source from one side. Some monitoring cases with borehole seismometers may achieve this geometry. Teleseismic location, especially for deep events, often achieves this geometry, but most of the ray paths are very long so there is large, accumulated travel-time error from velocity model error (especially around very 3D subduction zones!).

2. Ground-truth (GT) information such as a controlled explosion with known hypocenter and origin time, which is used to obtain station corrections. But the GT source must be near the target sources, so this procedure may not help with depth accuracy for a near surface GT explosion used to generate corrections for natural seismicity deeper in the crust.

3. Station(s) above the source with high quality P and S picks plus nearby surrounding stations with good P and perhaps S picks, *and* a very accurate velocity model. A very accurate velocity model is rare, but may be obtained with nearby well logs and/or integrated analysis of seismics, well logs, geology, etc. A model generated with earthquake arrival time picks (e.g. by layered inversion or tomography), is generally not adequate, as it uses the same data (picks) as will be used for location - a circular process, the obtained depths will be highly correlated with the depths obtained in the initial model. 

Effectively, for local/regional/microseismic location, accurate P and S picks are needed above the events, and the P and S travel-times (integrated slowness in the velocity model) along the near-vertical ray between the station and source must be highly accurate. With only stations at greater distance than the source depth, there is little hope - only very approximate and velocity-model dependent depths can be obtained. If there are adequate nearby stations, and the used model is close to the true earth structure and both give near-vertical rays at the source, then meaningful *relative* depths may be obtained.

Despite all these difficulties with true absolute depth, accurate absolute and especially relative epicenters can often be obtained since the azimuthal distribution and density of stations is often very good in well monitored seismic areas and with many experiments.

**Comment by Cthuulhaa** [comment]
Thank you so much for your extensive answer!
