### ISSUE TITLE
Question: purpose of EXTERN_TXT and EXTERN_MODE?

### ISSUE THREAD

**Issue by luca-s** [alomax/NonLinLoc#28]
I stumbled across the definition of EXTERN_TXT and EXTERN_MODE and I was wondering what is their purpose and logic. In my understanding declaring the variables `extern` in the header file and defining them only in one `.c' file would suffice. What am I missing?

I am asking this question due to a failed compilation and I would like to properly address the issue. thanks

**Comment by alomax** [comment]
As I recall (25-30 years ago!), this was a (standard?) way to allow multiple main programs to use common header files with global variables. So numerous variables are defined in header files instead of in .c files, but as they should only be defined (memory allocated) once for each main module, and only declared in other linked source files, they need to be flagged as `extern` (no memory allocated) when the header is included in a non-main source file.

**Comment by luca-s** [comment]
It looks like a compatibility issue of the (old) compilers with the `extern` behaviour. I wonder if that is still required. Thank you for the reply, you are always kind in answering my questions.

**Comment by alomax** [comment]
I suspect that `extern` or something equivalent is still required, as the C language syntax and specs have been very stable for a long time (unlike some recent languages...).

Please tell me if you find a solution to your compile problem and/or any further information on this issue.

Thanks,
Anthony

**Comment by luca-s** [comment]
For my compiler (gcc) it is enough to declare `extern`all the variables in the header files (the fuctions are `extern` by default) and then define only one time the variable in a single `.c` file. I have always thought this was the way to use `extern`. However I cannot test that on multiple compilers.

**Comment by alomax** [comment]
This sounds best if there is a single main .c file / program. But NonLinLoc has numerous principal and secondary main programs and utilities which would each have to define the global variables - a maintenance nighmare. Or is there another way...

**Comment by luca-s** [comment]
This is an example of how I have seen `extern` used in the past:

file1.h
```
extern int var1;
```
file1.c
```
#include "file1.h"
int var1 = 1;
```

file2.h
```
extern int var2;
```
file2.c
```
#include "file2.h"
int var2 = 2;
```

file3.h
```
extern int var3; 
void set();
```
file3.c
```
int var3 = -1;

void set()
{
  var3 = var1+var2;
}
```


main.c
```
#include "file1.h"
#include "file2.h"
#include "file3.h"
#include <stdio.h>

int main()
{
   printf("var1 %d var2 %d var3 %d\n", var1, var2, var3);
   set();
   printf("var1 %d var2 %d var3 %d\n", var1, var2, var3);
}
```

```
gcc file1.c file2.c file3.c main.c

````
./a.out 
var1 1 var2 2 var3 -1
var1 1 var2 2 var3 3
```

```

```

**Comment by luca-s** [comment]
What I meant with that example is that I would expect each individual library to **declare** in its header file the variables that it manages as  `extern` and also to **define** the variables somewhere but only once. The fact that a variable is **declared** `extern` doesn't clash with the **definition** of the variable in the source code. Pretty clean in my opinion. I am not sure this answers your question.

**Comment by alomax** [comment]
I guess what bothers me about this system is that each global variable needs to be defined and declared in separate files, instead of on one place as with the `EXTERN_TXT` system. It seems that the separate files would make maintainability and avoiding bugs (much) more difficult. And C already has the maintenance/compile difficulty of needing header files, unlike Java.
