### ISSUE TITLE
Question: why is RMS weighted by arrival weight?

### ISSUE THREAD

**Issue by luca-s** [alomax/NonLinLoc#29]
I stumbled across [this part](https://github.com/alomax/NonLinLoc/blob/700ed91a2f94d6996a2baa679475a6767dac137b/src/NLLocLib.c#L6396) of the code and I realized that the event RMS is weighted by arrival weight. While the weighting scheme has its interesting value, especially when comparing different NonLinLoc solutions this weighted RMS works as a score, I find the weighting to be an issue when comparing solutions across several locators or across different velocity models. In those cases I would rather have the RMS computed in the "standard" way, without arrival weights. That would make the value meaningful for comparison.

For this reason I would like to understand better why the RMS is computed the way it is.

Thanks.

**Comment by alomax** [comment]
Good question. The basic answer is that an RMS that is not weighted by arrival weight (quality, pick uncertainty, travel-time error, ...) can be highly biased by bad or outlier data and so not very informative. A weighted RMS is used in Hypoinverse:

[https://pubs.usgs.gov/of/1978/0694/report.pdf](https://pubs.usgs.gov/of/1978/0694/report.pdf)
<img width="920" alt="image" src="https://user-images.githubusercontent.com/11368512/185333737-5074369a-dacf-4adb-932f-0fc2483789b0.png">

However, there are complications in NLL depending on if the L2 GAU_ANALYTIC formulation of Tarantola and Valette 1982 [http://www.ipgp.fr/~tarantola/Files/Professional/Papers_PDF/IP_QI_latex.pdf](http://www.ipgp.fr/~tarantola/Files/Professional/Papers_PDF/IP_QI_latex.pdf) is used, in which case the weights are prior covariances on the picks and travel-time (Eq 10.9 in Tarantola and Valette 1982), and not sensitive to bad or outlier data.

Or a NLL EDT formulation, in which case the weights are the posterior contribution that the arrival makes to the EDT pdf stack. This is important because EDT intrinsically and efficiently down-weights outlier data so that their residuals can be very large, not including this posterior weight can give extremely large RMS in the presence of outlier data. But the EDT weights are a somewhat ad-hoc, hybrid of sums of probabilities, not simple covariances, so I doubt there is a clear or robust statistical basis for EDT weights and the resulting RMS. I tend to use the ellipsoid extent (len3 or se3, simple proxy for PDF extent) instead of RMS for filtering location results, along with sometimes number of readings, gap, or other prior measures.

In any case, the residuals are listed in the output, so an unweighted RMS can always be calculated.

Anthony

**Comment by luca-s** [comment]
Thank you very much for taking the time of answering, this is all good information.

**Comment by FMassin** [comment]
So, it is quite unfair to compare RMS from different location methods such as those included in SeisComP?
- LOCSAT uses [unweighted rms](https://github.com/SeisComP/common/blob/c2d63ec5226b879380d24f3dde7348ab47519b63/libs/seiscomp/seismology/locator/locsat.cpp#L883)
- hypo71 uses [rms without division by station number?](https://github.com/SeisComP/contrib-ipgp/blob/b9cb93804799bbdceb53f28c3d9488cc78e78a52/plugins/locator/hypo71/hypo71.cpp#L2206)
- iloc has both (called uRMS and wRMS) [but reports unweighted rms](https://github.com/SeisComP/main/blob/ee0cb2ec746776ee1b03e03573136e7405d0f0c6/plugins/locator/iloc/iloc.cpp#L1002)

**Comment by luca-s** [comment]
@FMassin As @alomax wrote "the residuals are listed in the output, so an unweighted RMS can always be calculated" so we should consider doing so in SED [NLL plugin for SeisComP](https://github.com/swiss-seismological-service/sed-SeisComP-contributions)

**Comment by alomax** [comment]
The rms from the hypo71 output seems to be parsed [here](https://github.com/SeisComP/contrib-ipgp/blob/b9cb93804799bbdceb53f28c3d9488cc78e78a52/plugins/locator/hypo71/hypo71.cpp#L3038). But hypo71 does use an rms "corrected for average P & S residual"
[https://pubs.usgs.gov/of/1972/0224/report.pdf](https://pubs.usgs.gov/of/1972/0224/report.pdf)
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/11368512/185401148-f5c76b2e-5b11-49c5-a929-fed708db902f.png">

But, in general (i.e. always), I would suppose that statistics from two different procedures (or even the same procedure with very different input configurations) cannot be directly compared. Perhaps, for the case of hypocenter location, only the statistics between events with similar station distribution, proportion of P and S picks, etc, within a single location configuration (velocity model, ...) and location algorithm, can be directly compared.

**Comment by FMassin** [comment]
> The rms from the hypo71 output seems to be parsed [here](https://github.com/SeisComP/contrib-ipgp/blob/b9cb93804799bbdceb53f28c3d9488cc78e78a52/plugins/locator/hypo71/hypo71.cpp#L3038). 

I think this is for the SeisComP interface. The actual hypo71 code is in https://github.com/SeisComP/contrib-ipgp/tree/master/apps/3rd-party/Hypo71PC.

**Comment by alomax** [comment]
Yeah - I was a bit confused, as the [link](https://github.com/SeisComP/contrib-ipgp/blob/b9cb93804799bbdceb53f28c3d9488cc78e78a52/plugins/locator/hypo71/hypo71.cpp#L2206) in the e-mail version of your comment pointed to the SCP interface...

In any case, [what hypo71 is doing with weights and AVRPS is not immediately clear](https://github.com/SeisComP/contrib-ipgp/blob/b9cb93804799bbdceb53f28c3d9488cc78e78a52/apps/3rd-party/Hypo71PC/single.f#L466)
 (FORTRAN!), but there is some possible weight `XWT`.

**Comment by FMassin** [comment]
Me too ! It took e a while to get it and edited my comment sorry!
