### ISSUE TITLE
Anisotropic velocity model

### ISSUE THREAD

**Issue by luca-s** [alomax/NonLinLoc#50]
Dear @alomax,

within a research project we have developed an anisotropic velocity model that we would like to use with NonLinLoc to locate earthquakes. I know that NonLinLoc doesn't natively support anisotropic velocity models, but we thought we could generate the necessary grid files using multiple 3D velocity models, one model for each station; each 3D velocity model would represent the velocity as seen by a specific station, which means the velocity at a specific point in the grid is dependent on the azimuth of the point and the station.

Do you believe something like this makes sense and would work?  Has this approach ever tried before?

thanks,
Luca

**Comment by alomax** [comment]
Hi @luca-s,

I have no practical experience with getting travel-times in anisotropic models, but have had some discussions on this topic.

One solution would be to calculate the travel-times outside NLL on a grid with a code that supports anisotropic models, and then write the travel-time grid in NLL grid format.

Another solution that *may* work when the anisotropy is constant and aligned along the x or y axis might be to adjust the the model grid so that the dx or dy grid step is nominally stretched or compressed. That is, NLL Grid2Time requires cubic grid cells with constant velocity in each cell; but after running Grid2Time, the cell dx or dy could be changed so that the original velocity value in that direction is the same as the anisotropic velocity in that direction. NLLoc location does not require cubic grids, so dx, dy, dz do not have to be equal. This solution may be similar or equivalent to yours, but does not require special velocity grids for each station. Though your solution may support constant anisotropy at arbitrary horizontal and vertical angles? Though NLL can work with an azimuthally rotated grid and thus x, y (horizontal) orientation.

I hope this helps, sorry I do not have a specific solution,

Best regards,

Anthony

**Comment by luca-s** [comment]
Thank you very much @alomax. As usual you are very helpful and kind in answering quickly to to my questions.

**Comment by alomax** [comment]
👍🏼
